# Generated by Django 2.1.2 on 2018-10-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctionApp', '0009_remove_auction_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='active',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='banned',
        ),
    ]
