# Generated by Django 2.1.2 on 2018-10-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionApp', '0010_auto_20181023_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
