# Generated by Django 2.1.2 on 2018-10-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionApp', '0018_auto_20181024_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='active',
        ),
        migrations.AddField(
            model_name='auction',
            name='lifecycle',
            field=models.CharField(choices=[('A', 'Active'), ('B', 'Banned'), ('D', 'Due'), ('E', 'Adjudicated')], default='A', max_length=1),
        ),
    ]
