# Generated by Django 2.1.2 on 2018-10-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionApp', '0019_auto_20181024_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
