# Generated by Django 2.1.2 on 2018-10-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctionApp', '0020_auction_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='updated',
        ),
    ]
